------------------------------------------------------------------------------------------------------<br>
<h3 style="background:#87a1c2; color:#ffffff; padding:20px; border-radius:5px;">✍ EJERCICIOS NUMPY PARA @EGGERS</h3><br>
------------------------------------------------------------------------------------------------------<br>

1. Crea un vector entre 7 y 66.
2. Invierte el vector generado anteriormente.
3. Matriz de 4x4 con valores entre 0 y 15.
5. Crea la matriz identidad de 5x5.
6. Crea una matriz de 5x5 donde la posición central y todas las posiciones que conforman el marco valgan 1 y el resto 0.
7. Matriz de 4x4 donde cada fila valga entre 3 y 0. Valores in crescendo.
8. Crea un array de ceros de 2x7.
9. Crea un array de ceros de 5x4 excepto toda la primera fila que valga 1.
10. Crea un array que represente una tabla de ajedrez. Negras 1 y blancas 0.

In [1]:
import numpy as np

In [2]:
a=np.arange(7,67)

In [4]:
a.shape

(60,)

In [5]:
a

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
       41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57,
       58, 59, 60, 61, 62, 63, 64, 65, 66])

In [6]:
res = a[::-1]

In [7]:
res

array([66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50,
       49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7])

In [13]:
b=np.arange(0,16).reshape(4,4)

In [14]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
c=np.zeros((4,4),int)

In [21]:
c

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
d=np.identity(5)

In [25]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [47]:
e=np.zeros((5,5))

In [48]:
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
e=np.zeros((5,5))
e[0,0:5]=1
e[4,0:5]=1
for h in range(1,5):
    e[h,::4]=1
e[2,2]=1

In [52]:
e

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
g=np.zeros((2,7),dtype=int)

In [62]:
g

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [73]:
j=np.zeros((4,4),int)

In [74]:
j

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [75]:
for x in range(0,4):
    j[x,0:4]=np.arange(0,4)

In [76]:
j

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [65]:
i=np.zeros((5,4),dtype=int)
i[0,0:4]=1

In [66]:
i

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [97]:
k=np.zeros((8,8),dtype=str)
k[0,0:8]=1
k[1,0:8]=1
k[6,0:8]=0
k[7,0:8]=0

In [98]:
k

array([['1', '1', '1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1', '1', '1'],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', ''],
       ['0', '0', '0', '0', '0', '0', '0', '0'],
       ['0', '0', '0', '0', '0', '0', '0', '0']], dtype='<U1')